name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "overlays/**"
      - "flake.lock"
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
            target: .#homeConfigurations.hani.activationPackage
          - os: macos-latest
            name: macOS
            target: .#darwinConfigurations.Mac.system
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v15
        with:
          name: vomba
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ github.event_name == 'pull_request' }}
      - name: Check formatting
        run: |
          shopt -s globstar
          nix run nixpkgs#nixfmt -- --check flake.nix home.nix linux.nix darwin.nix modules/**/*.nix overlays/*.nix
      - name: Check flake
        run: nix flake check
      - name: ShellCheck
        run: shellcheck scripts/*.sh
      - name: Build configuration
        run: nix build ${{ matrix.target }} --no-link
